export function level6(){
        let level = addLevel([
                "5                                          5",
                "5                                          5",
                "5                C C C C   G               5",
                "5      5555555555555555555555555555        5",
                "5 X           5                            5",
                "555           5                            5",
                "5  5          5                    C      C5",
                "5   5         5                   5555555555",
                "5    555      5                  5         5",
                "5          X 5                  5          5",
                "5          55                  5           5",
                "5        55                   5            5",
                "5       5                                  5",
                "5      5               C    C   X    5     5",
                "55555555555555555555555555555555555555     5",
                "                                     5     5",
                "                                     5     5",
                "                                     5     5",
                "                                     5     5",
                "                                     5  O  5",
                "                                     5555555",
            ],{
                tileWidth: 64,
                tileHeight: 64,

                pos: vec2(0, 0),

                tiles: {
                    "1": () => [
                        sprite("tile1"),
                        area(),
                        outline(2),
                        body({isStatic: true}),
                        tile({isObstacle: true}),
                        "tile",
                    ],
                    "2": () => [
                        sprite("tile2"),
                        area(),
                        outline(2),
                        body({isStatic: true}),
                        tile({isObstacle: true}),
                        "tile",
                    ],
                    "3": () => [
                        sprite("tile3"),
                        area(),
                        outline(2),
                        body({isStatic: true}),
                        tile({isObstacle: true}),
                        "tile",
                    ],
                    "4": () => [
                        sprite("tile4"),
                        area(),
                        outline(2),
                        body({isStatic: true}),
                        tile({isObstacle: true}),
                        "tile",
                    ],
                    "5": () => [
                        sprite("tile5"),
                        area(),
                        //outline(2),
                        body({isStatic: true}),
                        //color(0, 0, 255),
                        tile({isObstacle: true}),
                        "tile",
                    ],
                    "=": () => [
                        rect(60,60),
                        area(),
                        outline(2),
                        body({isStatic: true}),
                        color(127, 200, 255),
                        tile({isObstacle: true}),
                        "tile",
                    ],
                    "P": () => [
                        rect(60,60),
                        area(),
                        outline(2),
                        body({isStatic: true}),
                        color(0, 0, 255),
                        tile({isObstacle: true}),
                        "tile",
                    ],
                    "O": () => [
                        rect(640,40),
                        area(),
                        opacity(0),
                        body({isStatic: true}),
                        outline(4),
                        anchor("center"),
                        color(0,255,0),
                        "goal",
                    ],
                    "X": ()=>[
                        rect(0, 0),
                        area(),
                        "spawnpoint1",  
                    ],
                    "C": ()=>[
                        rect(0, 0),
                        area(),
                        "spawnpoint2",  
                    ],
                    "Y": ()=>[
                        rect(0, 0),
                        area(),
                        "spawnpoint3",  
                    ],
                    "G": ()=>[
                        rect(64,300),
                        opacity(0),
                        area(),
                        anchor("bot"),
                        "dialogue",  
                    ], 

                }
            })
            return level
    }
